### ISSUE TITLE
Pub get fails in flutter dev channel 

### ISSUE THREAD

**Issue by archie-sh** [marcglasberg/weak_map#2]
> /Users/private/development/flutter/bin/flutter --no-color pub get
Running "flutter pub get" in private...                          

> Because weak_map 1.2.1 depends on meta 1.1.8 and no versions of weak_map match >1.2.1 <2.0.0, weak_map ^1.2.1 requires meta 1.1.8.
> And because every version of flutter from sdk depends on meta 1.3.0-nullsafety and async_redux 3.0.0 depends on weak_map ^1.2.1, flutter from sdk is incompatible with async_redux 3.0.0.
> So, because private depends on both flutter any from sdk and async_redux 3.0.0, version solving failed.
> pub get failed (1; So, because private depends on both flutter any from sdk and async_redux 3.0.0, version solving failed.)
> Process finished with exit code 1

May I suggest setting the meta dependency to 

`meta: ^1.1.8`

**Comment by marcglasberg** [comment]
Done. See version [1.2.2].
