### ISSUE TITLE
Migrating to null safety

### ISSUE THREAD

**Issue by SunlightBro** [marcglasberg/weak_map#3]
Migrating to null safety, as [async_redux](https://github.com/marcglasberg/async_redux) is depending on it.

**Comment by marcglasberg** [comment]
Thanks for the PR! With 12 packages and going to 13, I really need some help from the community with the null safety migration.

Regarding that test, I should never have trusted this would be future proof, of course:

```dart
String otherA = "a" ""; // Concatenate.
```

I will remake this test as soon as I can.

**Comment by SunlightBro** [comment]
[2.0.0-nullsafety.1](https://pub.dev/packages/weak_map/versions/2.0.0-nullsafety.1) released, closing this issue.
