### ISSUE TITLE
WeakMap:  Consider explicitly documenting object identity vs. equivalence for keys

### ISSUE THREAD

**Issue by zathras** [marcglasberg/weak_map#5]
Hi!  I have a gentle documentation/specification suggestion for WeakMap.  I think it would be helpful to explicitly specify that they keys are compared using object identity, and not object equivalence.  This might not be obvious to people trying to use the class, particularly if they're not familiar with Expando.  It could be especially surprising for folks familiar with Java's WeakHashMap, which of course uses object equivalence, and not identity for the keys.  Indeed, this property is essential for WeakHashMap's primary use case, canonicalizing mappings, and it's generally what "map" means.

For reference, my process was this:
a) I need canonicalizing mappings.  Can I do this with dart?
b) Well, I know Expando doesn't get me there.
c) I wonder what the status is of adding weak reference to dart?  (FWIW:  https://github.com/dart-lang/language/blob/master/working/1847%20-%20FinalizationRegistry/proposal.md)
d) Hey!  There's a WeakMap package out there!
e) Oh.  It's an identity map, too.  Oh well.

:-)

**Comment by marcglasberg** [comment]
Thanks for the suggestion. 

Could you please help me with that? Where exactly in the documentation would you add this explanation, and what exactly do you suggest I write there?

**Comment by marcglasberg** [comment]
Added to version [2.0.4].
